apiVersion: v1
kind: Service
metadata:
  name: hackathon
  labels:
    app: hackathon
spec:
  type: LoadBalancer
  selector:
    app: hackathon
  ports:
    - protocol: TCP
      name: http
      port: 8082
      targetPort: 8082
      nodePort: 30005