apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon
  labels:
    app: hackathon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hackathon
  template:
    metadata:
      labels:
        app: hackathon
    spec:
      containers:
      - name: hackathon
        image: daniel36/hackathon-ponto-eletronico:latest
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8082
        resources:
          limits:
            cpu: 0.2
            memory: "512Mi"
        env:
          - name: MONGO_HOST
            value: mongo-db
          - name: MONGO_USERNAME
            valueFrom:
              configMapKeyRef:
                name: mongo-config-map
                key: mongo-username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-password

          - name: TOKEN_SECURITY
            valueFrom:
              secretKeyRef:
                name: token-security
                key: TOKEN_SECURITY
          - name: EMAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: email-password
                key: EMAIL_PASSWORD


---
